// J4 — budget commands plan only; the Budgets page writes, only after its own Save / Done.
import { test, expect } from '../support/fixtures.js'

test("J4: create next month's budget — rows appear only after Done, for November", async ({ app, page }) => {
  await app.open('/')
  const start = await app.counts()
  await app.say("Create next month's budget")
  await expect(app.btn('Continue in Budgets')).toBeVisible()
  expect(await app.writes()).toEqual([])
  await app.btn('Continue in Budgets').click()
  await expect(page.getByRole('heading', { name: 'Pool your monthly expenses', exact: true })).toBeVisible()
  await expect(page.locator('#budget-month')).toHaveValue('2026-11')
  expect(await app.writes(), 'opening the recipe saves nothing').toEqual([])
  await page.locator('textarea').last().fill('rent 8000, travel 2000')
  await app.btn('Build Budget →').click()
  await app.btn('Done').click({ timeout: 10_000 })
  await expect.poll(async () => (await app.writeTables()).length).toBe(2)
  expect(app.delta(start, await app.counts())).toEqual({ budgets: 2 })
  const rows = (await app.rows('budgets')).filter((b) => b.period_start === '2026-11-01')
  expect(rows).toHaveLength(2)
  expect(rows.every((b) => b.period_end === '2026-11-30' && b.period_type === 'monthly')).toBe(true)
  expect((await app.rows('budgets')).find((b) => b.id === 'b1').amount, 'October is unchanged').toBe(4500)
  expect((await app.rows('transactions')).length, 'a budget is never spending').toBe(start.transactions)
})

test('J4b: change a budget amount — one update, only that row', async ({ app, page }) => {
  await app.open('/')
  const start = await app.counts()
  await app.say('Set my rent budget to 5000')
  await app.btn('Continue in Budgets').click()
  await expect(page.locator('#budget-amount')).toHaveValue('5000')
  expect(await app.writes()).toEqual([])
  await page.locator('dialog').getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.locator('dialog')).toHaveCount(0)
  expect(app.delta(start, await app.counts())).toEqual({})
  expect(await app.writeTables()).toEqual(['budgets:update'])
  const b = await app.rows('budgets')
  expect(b.find((x) => x.id === 'b1').amount).toBe(5000)
  expect(b.find((x) => x.id === 'b2').amount).toBe(1000)
})
