// The most important test in this directory. Proves the plain-JS scorer
// reproduces the actual trained Python model's predictions — not "seems
// reasonable", but agrees on every example in model/g1_predictions_reference.json,
// which was generated by g1_training/train.py calling the real sklearn
// model directly. A silent mismatch here would mean the deployed app and
// the reported accuracy numbers describe two different models.
import assert from 'node:assert'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { categorizeMl, ML_MODEL_VERSION, ML_CONFIDENCE_THRESHOLD } from './categorizeMl.js'
import model from './model/g1_model.json' with { type: 'json' }

let passed = 0, failed = 0
function test(name, fn) {
  try { fn(); passed++; console.log(`  PASS  ${name}`) }
  catch (err) { failed++; console.log(`  FAIL  ${name}\n        ${err.message}`) }
}

const reference = JSON.parse(readFileSync(
  fileURLToPath(new URL('./model/g1_predictions_reference.json', import.meta.url)), 'utf8'))

console.log('categorizeMl faithfulness tests\n')

test('the reference file itself is non-trivial (the check below is not vacuous)', () => {
  assert.ok(reference.length > 500, `only ${reference.length} reference rows`)
})

test('metadata matches the trained model exactly', () => {
  assert.strictEqual(ML_MODEL_VERSION, model.modelVersion)
  assert.strictEqual(ML_CONFIDENCE_THRESHOLD, model.confidenceThreshold)
})

// ---- The core faithfulness check: category AND confidence, every row ----
test('every reference example: JS predicted category matches Python exactly', () => {
  const mismatches = []
  for (const row of reference) {
    const result = categorizeMl(row.text)
    const expectedCategory = row.confidence >= model.confidenceThreshold ? row.predictedCategory : null
    if (result.category !== expectedCategory) {
      mismatches.push({ text: row.text, jsCategory: result.category, pythonCategory: expectedCategory })
    }
  }
  assert.strictEqual(mismatches.length, 0, `${mismatches.length} mismatches, e.g. ${JSON.stringify(mismatches.slice(0, 5))}`)
})

test('every reference example: JS confidence matches Python\'s within floating-point tolerance', () => {
  let worst = 0
  const bad = []
  for (const row of reference) {
    const result = categorizeMl(row.text)
    const diff = Math.abs(result.confidence - row.confidence)
    worst = Math.max(worst, diff)
    if (diff > 1e-6) bad.push({ text: row.text, js: result.confidence, python: row.confidence, diff })
  }
  assert.deepStrictEqual(bad, [], `worst diff seen: ${worst}`)
})

test('probabilities for one example sum to ~1 (a valid softmax distribution)', () => {
  const { allProbabilities } = categorizeMl(reference[0].text)
  const sum = Object.values(allProbabilities).reduce((a, b) => a + b, 0)
  assert.ok(Math.abs(sum - 1) < 1e-9, `sum=${sum}`)
})

// ---- Tokenization edge cases, verified against sklearn's ACTUAL behavior --
// ---- (empirically checked with build_analyzer(), not assumed) ------------
test('a single-letter word is dropped, exactly like sklearn\'s default token pattern', () => {
  // categorizeMl has no direct tokenize export, so this is checked indirectly:
  // a sentence differing only by "a" must produce IDENTICAL features/output.
  const a = categorizeMl('biryani amtnum from a canteen stall')
  const b = categorizeMl('biryani amtnum from canteen stall')
  assert.deepStrictEqual(a, b)
})

test('bigrams skip the dropped word rather than treating it as a gap-filler', () => {
  // "from a canteen" must bigram as "from canteen" (matching sklearn's
  // build_analyzer output verified during training), not "from a" + "a canteen".
  // Proven the same way: any sentence containing a genuine "from a X" bigram
  // that would only exist if "a" were kept must score identically to one
  // with "a" removed outright.
  const withA = categorizeMl('paid from a store today')
  const withoutA = categorizeMl('paid from store today')
  assert.deepStrictEqual(withA, withoutA)
})

test('an amount value never changes the prediction — only its presence/format might, never its magnitude', () => {
  const cheap = categorizeMl('biryani 40')
  const expensive = categorizeMl('biryani 99999')
  assert.deepStrictEqual(cheap, expensive)
})

test('an unknown word (out of vocabulary) does not throw and degrades gracefully', () => {
  assert.doesNotThrow(() => categorizeMl('zzqxw flibbertigibbet 40'))
})

test('empty and whitespace-only input does not throw', () => {
  assert.doesNotThrow(() => categorizeMl(''))
  assert.doesNotThrow(() => categorizeMl('   '))
})

test('low confidence produces category=null (abstention), never a forced guess', () => {
  const r = categorizeMl('zzqxw flibbertigibbet 40')
  assert.strictEqual(r.category, null)
  assert.ok(r.confidence < ML_CONFIDENCE_THRESHOLD)
})

console.log(`\n${passed} passed, ${failed} failed`)
if (failed > 0) process.exit(1)
